### ISSUE TITLE
panic: runtime error: slice bounds out of range [2527:2525]

### ISSUE THREAD

**Issue by jaimeph** [achetronic/hitman#2]
```
{"level":"info","timestamp":"2024-11-27T19:47:31Z","msg":"starting Hitman. Getting ready to kill some targets"}
{"level":"info","timestamp":"2024-11-27T19:47:31Z","msg":"syncing resources"}
...
{"level":"info","timestamp":"2024-11-27T19:48:37Z","msg":"resource 'ff5841b-cd-stable-videvo-fqvne' in namespace 'videvo' did NOT meet the conditions"}
panic: runtime error: slice bounds out of range [2527:2525]

goroutine 1 [running]:
hitman/internal/processor.deleteItemByIndex(...)
    /workspace/internal/processor/utils.go:8
hitman/internal/processor.(*Processor).SyncResources(0xc0003a7c38)
    /workspace/internal/processor/processor.go:98 +0x1405
hitman/internal/cmd/run.RunCommand(0xc0001a1808, {0x1772dc7?, 0x4?, 0x1772dcb?})
    /workspace/internal/cmd/run/run.go:109 +0x645
github.com/spf13/cobra.(*Command).execute(0xc0001a1808, {0xc0002685c0, 0x4, 0x4})
    /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a1208)
    /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x7ffcea65bde7?)
    /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
    /workspace/cmd/main.go:13 +0x35
stream closed EOF for hitman/hitman-6757d767d4-rbvk6 (agent)
```

**Comment by jaimeph** [comment]
It is not advisable to remove an item from a scrolling list.
https://github.com/achetronic/hitman/blob/master/internal/processor/processor.go#L98C5-L98C22

**Comment by achetronic** [comment]
Hey, you are completely right. LGTM and thank you for the fix!! :)

approved
